### ISSUE TITLE
Ansible host alias should be 'micado-master' instead of 'localhost'

### ISSUE THREAD

**Issue by atisu** [micado-scale/ansible-micado#1]
### Prerequisites

* [x] Can you reproduce the problem?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?

### Description

Ansible host alias should be 'micado-master' instead of 'localhost' for all playbooks and host inventory.

### Versions

0.3.x

**Comment by maystery** [comment]
Localhost variable replaced in this commit: https://github.com/micado-scale/ansible-micado/commit/845fa2bee834eb1a568f4e0a2105b37914995806
