### ISSUE TITLE
Where is the code of genetic of algorithm part？

### ISSUE THREAD

**Issue by donydex** [micado-scale/ansible-micado#161]
Hi Sir，recently I had read the paper you published about MicADO, it is a great paper and i would like to see the detail part about genetic algorithms code about MicADO， but i can‘t find that. Could you please tell me where is the code of GA part about MicADO? I'll be thanksful for your help!

**Comment by smith4** [comment]
Dear donydex, We have several papers published on MiCADO. Could you please, let us know the details (title, author, url) of the paper in which you have read about the Genetic algorithms? Thank you in advance.

**Comment by donydex** [comment]
Thanks,i just see this reply.The paper i read is that "Workload-based Clustering of Coherent Feature
Sets in Microservice Architectures".(https://ieeexplore.ieee.org/document/7930194)Thank you you very much!

**Comment by donydex** [comment]
Thanks,i just see this reply.The paper i read is that "Workload-based Clustering of Coherent Feature
Sets in Microservice Architectures".( https://ieeexplore.ieee.org/document/7930194 ) Thank you you very much!

**Comment by smith4** [comment]
Dear donydex, The paper you are referring to does not belong to our group and the MicADO tool it details is not the one under this repository. There is unfortunately a name conflict. My suggestion is to write an email to the authors of that paper. Hope you will be able find the right repository and developers. Bye.

**Comment by donydex** [comment]
Tank you very much!
