### ISSUE TITLE
fatal error when {{ in the password credentials-cloud-api

### ISSUE THREAD

**Issue by gregGes** [micado-scale/ansible-micado#181]
### Prerequisites

* [x] Can you reproduce the problem?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?

### Description

When having a {{ character in the password credentials-cloud-api.yml even with quotes, during the launch of the playbook ansible is Failing with Fatal Error.

### Steps to Reproduce

1. put a {{ character in the string of the pwd
2. launch the playbook

**Expected behavior:** 
install MiCADO master smoothly 

**Actual behavior:**
following is an example with a fake pwd abc{{ 

fatal: [micado-master]: FAILED! => {"changed": false, "msg": "AnsibleError: An unhandled exception occurred while templating '{u'resource': [{u'auth_data': {u'secretkey': None, u'accesskey': None}, u'type': u'ec2'}, {u'auth_data': {u'password': u'abc{{', u'email': u'email@westminster.ac.uk'}, u'type': u'cloudsigma'}, {u'auth_data': {u'password': None, u'email': None}, u'type': u'cloudbroker'}, {u'auth_data': {u'username': None, u'password': None}, u'type': u'nova'}]}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: unexpected 'end of template'. String: abc{{"}
### Versions

[MiCADO verison]
v0.7.2
### Additional context
this isn't happening when there's only one {

**Comment by maystery** [comment]
This is the expected behaviour in Ansible. You can avoid that with `!unsafe` tag. Further information here:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_advanced_syntax.html#id1
