### ISSUE TITLE
MiCADO Master and workers generated hostname

### ISSUE THREAD

**Issue by atisu** [micado-scale/ansible-micado#2]
### Prerequisites

* [x] Can you reproduce the problem?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?

### Description

Generated hostname for micado master and workers  should follow the  format _micado-{master/worker}-< ip with dot replaced with dash >_

### Steps to Reproduce

None required.

### Versions

0.3.x

**Comment by maystery** [comment]
97c257dbe7ce1b057646da9741122efb7dc9e1d3 commit should solve this
