### ISSUE TITLE
Ability to add tags to AWS provisioned instances

### ISSUE THREAD

**Issue by nicksellen** [micado-scale/ansible-micado#24]
For accounting purposes it is useful to specify tags on AWS instances (and other resources). To achieve this is would be useful to be able to specify arbitary key/value pairs that will be applied to any instance that is provisioned during scaling.

**Comment by maystery** [comment]
This feature now available in [v0.7.3](https://github.com/micado-scale/ansible-micado/releases/tag/v0.7.3).
