### ISSUE TITLE
Support rebooting of the master

### ISSUE THREAD

**Issue by nicksellen** [micado-scale/ansible-micado#25]
Currently it is not possible to reboot the master node, if any changes are needed, or it shuts down, then the whole cluster needs to be reprovisioned from scratch.

**Comment by blint** [comment]
The security branch features a systemd unit file that should take care of this, but we haven't discussed its course of integration into master yet: https://github.com/micado-scale/ansible-micado/commit/c2403e1be8b730f1eaaf8d8e4240dde4e14a9bf2

**Comment by jaydesl** [comment]
This is supported, so long as the Master node IP is unchanged on reboot
