### ISSUE TITLE
Don't reinitialize swarm on playbook rerun

### ISSUE THREAD

**Issue by nicksellen** [micado-scale/ansible-micado#60]
When re-running the playbook on an already (at least partially configured) cluster it gets to the *Docker Swarm: Initialization* task (basically `docker swarm init`) then fails with
```
Error response from daemon: This node is already part of a swarm
```

It should handle this case for reruns. For now I just have to comment out that task for re-runs.

**Comment by blint** [comment]
This patch on the security branch should handle this: https://github.com/micado-scale/ansible-micado/commit/7023d498da938a6cb235f457fb4abc8b69f7cf46

**Comment by fsattila** [comment]
I've merged the https://github.com/micado-scale/ansible-micado/commit/7023d498da938a6cb235f457fb4abc8b69f7cf46 commit and I've set a guard to the docker daemon restart.
