### ISSUE TITLE
Better handling of occopus log directory

### ISSUE THREAD

**Issue by nicksellen** [micado-scale/ansible-micado#61]
I had a scenario, probably after re-running the playbook after a partial failure, where the occopus container failed to start with two errors in the log:
```
mkdir: cannot create directory '/var/log/occopus': File exists
```
and:
```
ValueError: Unable to configure handler 'datafile': [Errno 2] No such file or directory: '/var/log/occopus/var/log/occopus/occopus-data.log
```
I resolved by changing the volume mount definition in docker-compose.yml from:
```
- "/var/log/micado/occopus/:/var/log/occopus/"
```
to:
```
- "/var/log/micado/:/var/log/"
```

**Comment by fsattila** [comment]
This is an Occopus related issue which is fixed in that PR: https://github.com/occopus/master/pull/2
The currently used Occopus docker image (micado/occopus:1.6-rc1) is updated on Docker Hub.
