### ISSUE TITLE
Strange API output

### ISSUE THREAD

**Issue by nicksellen** [micado-scale/ansible-micado#62]
I find the output of the API not super useful.

Retrieving a list of deployed applications returns something between html and json:
```
curl -X GET http://localhost:5050/v1.0/list_app/
<h1>here is the id list of applications 
 ['id: simpleapp, outputs: {}\n']
</h1>
```

Fetching details for a single application gives me a string with an empty object in it:
```
curl -X GET http://localhost:5050/v1.0/app/simpleapp
{"message":"{}"}
```

**Comment by jaydesl** [comment]
Responses from both endpoints have been improved in the master branch of **micado-scale/component_submitter**. Changes will be reflected when the ansible-micado repository is updated.



*Sample response*
```
{
  "data": [
    {
      "components": [
        "Docker",
        "Occo"
      ],
      "id": "app123",
      "outputs": "this is some output",
      "type": "application"
    }
  ],
  "message": "List running applications",
  "status_code": 200
}
```
